if __name__ == "__main__":
#     cart_record, catalog_record, checkout_record, customer_record, login_access_record, address_record, manufacturer_record, category_record, dimension_record, payment_record, shipping_record = generate_fake_data()
#     print("Records created successfully!")
#     print("cart_record: ", cart_record)
#     print("catalog_record: ", catalog_record)
#     print("checkout_record: ", checkout_record)
#     print("customer_record: ", customer_record)
#     print("login_access_record: ", login_access_record)
#     print("address_record: ", address_record)
#     print("manufacturer_record: ", manufacturer_record)
#     print("category_record: ", category_record)
#     print("dimension_record: ", dimension_record)
#     print("payment_record: ", payment_record)
#     print("shipping_record: ", shipping_record)
